BackboneModel: !!python/name:models.MURA.Model ''
batch_size: 512
data_params:
  data_path: ETTm2.csv
  embed: timeF
  enc_in: 7
  features: M
  freq: M
  label_len: 0
  loader: ETTm2
  name: ETTm2
  pred_len: 96
  root_path: /data/songzy/workshop/data/time_series/long_tf/ETT-small/
  seq_len: 336
  target: OT
  visual_cs:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
net_params:
  channels: 7
  d_model: 128
  features: M
  lr: 0.005
  name: MURA
  norm_type: seq
  pred_len: 96
  seq_len: 336
  stride: 24
  trend_freq: 0.9
  visual_cs: 0
