_target_: lightning.pytorch.trainer.Trainer
accelerator: cpu
devices: 1
max_epochs: 1
min_epochs: 1
limit_train_batches: 1
check_val_every_n_epoch: 1
limit_val_batches: 1
limit_test_batches: 1 
fast_dev_run: False
