BackboneModel: !!python/name:models.MURA.Model ''
batch_size: 256
data_params:
  data_path: exchange_rate.csv
  embed: timeF
  enc_in: 8
  features: M
  freq: h
  label_len: 0
  loader: custom
  name: Exchange_rate
  pred_len: 192
  root_path: /data/songzy/workshop/data/time_series/long_tf/exchange_rate/
  seq_len: 96
  target: OT
  visual_cs:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
net_params:
  channels: 8
  d_model: 128
  features: M
  lr: 0.005
  name: MURA
  norm_type: 'no'
  pred_len: 192
  seq_len: 96
  stride: 1
  trend_freq: 0.5
  visual_cs: 0
