BackboneModel: !!python/name:models.MURA.Model ''
batch_size: 64
data_params:
  data_path: illness.csv
  embed: timeF
  enc_in: 7
  features: M
  freq: h
  label_len: 0
  loader: custom
  name: ILI
  pred_len: 36
  root_path: /data/songzy/workshop/data/time_series/long_tf/illness/
  seq_len: 96
  target: OT
  visual_cs:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
net_params:
  channels: 7
  d_model: 64
  features: M
  lr: 0.01
  name: MURA
  norm_type: seq
  pred_len: 36
  seq_len: 96
  stride: 1
  trend_freq: 0.1
  visual_cs: 0
