BackboneModel: !!python/name:models.MURA.Model ''
batch_size: 512
data_params:
  data_path: ETTh1.csv
  embed: timeF
  enc_in: 7
  features: M
  freq: h
  label_len: 0
  loader: ETTh1
  name: ETTh1
  pred_len: 96
  root_path: /data/songzy/workshop/data/time_series/long_tf/ETT-small/
  seq_len: 336
  target: OT
  visual_cs:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
net_params:
  channels: 7
  d_model: 128
  features: M
  lr: 0.05
  name: MURA
  norm_type: seq
  pred_len: 96
  seq_len: 336
  stride: 12
  trend_freq: 0.7
  visual_cs: 0
